/*******************************************************************************
 * This file is part of SWIFT.
 * Copyright (c) 2013 Pedro Gonnet (pedro.gonnet@durham.ac.uk)
 *                    Matthieu Schaller (schaller@strw.leidenuniv.nl)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 ******************************************************************************/
#ifndef SWIFT_MULTI_SOFTENING_GRAVITY_IACT_H
#define SWIFT_MULTI_SOFTENING_GRAVITY_IACT_H

/* Includes. */
#include "kernel_gravity.h"
#include "kernel_long_gravity.h"
#include "multipole.h"

/* Standard headers */
#include <float.h>
#ifdef __ARM_NEON
#include <arm_neon.h>
#endif


/**
 * @brief Computes the intensity of the force at a point generated by a
 * point-mass.
 *
 * The returned quantity needs to be multiplied by the distance vector to obtain
 * the force vector.
 *
 * @param r2 Square of the distance to the point-mass.
 * @param h2 Square of the softening length.
 * @param h_inv Inverse of the softening length.
 * @param h_inv3 Cube of the inverse of the softening length.
 * @param mass Mass of the point-mass.
 * @param f_ij (return) The force intensity.
 * @param pot_ij (return) The potential.
 */
__attribute__((always_inline, nonnull)) INLINE static void
runner_iact_grav_pp_full(const float r2, const float h2, const float h_inv,
                         const float h_inv3, const float mass,
                         float *restrict f_ij, float *restrict pot_ij) {

  /* Get the inverse distance */
  const float r_inv = 1.f / sqrtf(r2 + FLT_MIN);

  /* Should we soften ? */
  if (r2 >= h2) {

    /* Get Newtonian gravity */
    *f_ij = mass * r_inv * r_inv * r_inv;
    *pot_ij = -mass * r_inv;

  } else {

    const float r = r2 * r_inv;
    const float ui = r * h_inv;
    const float W_f_ij = kernel_grav_force_eval(ui);
    const float W_pot_ij = kernel_grav_pot_eval(ui);

    /* Get softened gravity */
    *f_ij = mass * h_inv3 * W_f_ij;
    *pot_ij = mass * h_inv * W_pot_ij;

  }
}

#ifdef __ARM_NEON

/**
 * @brief NEON vectorized pp force interaction with 4 pairs at once.
 *
 * Computes the force intensity and potential for 4 particle pairs using
 * NEON SIMD. Uses vrsqrteq_f32 for reciprocal sqrt (with Newton-Raphson
 * refinement) and vbslq_f32 for branch-free Newtonian/softened selection.
 */
__attribute__((always_inline, nonnull)) INLINE static void
runner_iact_grav_pp_full_neon(
    const float32x4_t r2, const float32x4_t h2,
    const float32x4_t h_inv, const float32x4_t h_inv3,
    const float32x4_t mass, float32x4_t *restrict f_ij,
    float32x4_t *restrict pot_ij) {

  /* Guard against division by zero (matching scalar r2 + FLT_MIN) */
  float32x4_t r2_safe = vaddq_f32(r2, vdupq_n_f32(FLT_MIN));

  /* r_inv = 1/sqrt(r2) via reciprocal sqrt estimate + Newton step */
  float32x4_t r_inv_est = vrsqrteq_f32(r2_safe);
  float32x4_t half = vdupq_n_f32(0.5f);
  float32x4_t step = vrsqrtsq_f32(r2_safe, vmulq_f32(r_inv_est, r_inv_est));
  float32x4_t r_inv = vmulq_f32(vmulq_f32(half, r_inv_est), step);

  /* mask: r2 >= h2 -> Newtonian, else softened */
  uint32x4_t mask_newton = vcgeq_f32(r2, h2);

  /* === Newtonian path (r >= h) === */
  float32x4_t r_inv3 = vmulq_f32(r_inv, vmulq_f32(r_inv, r_inv));
  float32x4_t f_newton = vmulq_f32(mass, r_inv3);
  float32x4_t pot_newton = vmulq_f32(vnegq_f32(mass), r_inv);

  /* === Softened path (r < h) === */
  float32x4_t r = vmulq_f32(r2, r_inv);
  float32x4_t ui = vmulq_f32(r, h_inv);
  float32x4_t W_f = kernel_grav_force_eval_neon(ui);
  float32x4_t W_pot = kernel_grav_pot_eval_neon(ui);
  float32x4_t f_soft = vmulq_f32(mass, vmulq_f32(h_inv3, W_f));
  float32x4_t pot_soft = vmulq_f32(mass, vmulq_f32(h_inv, W_pot));

  /* Merge paths via bitwise select */
  *f_ij = vbslq_f32(mask_newton, f_newton, f_soft);
  *pot_ij = vbslq_f32(mask_newton, pot_newton, pot_soft);
}

/**
 * @brief NEON vectorized truncated pp force for periodic BCs.
 */
__attribute__((always_inline, nonnull)) INLINE static void
runner_iact_grav_pp_truncated_neon(
    const float32x4_t r2, const float32x4_t h2,
    const float32x4_t h_inv, const float32x4_t h_inv3,
    const float32x4_t mass, const float32x4_t r_s_inv,
    float32x4_t *restrict f_ij, float32x4_t *restrict pot_ij) {

  /* Compute base PP interaction */
  runner_iact_grav_pp_full_neon(r2, h2, h_inv, h_inv3, mass, f_ij, pot_ij);

  /* Compute distance r for long-range correction (matching scalar) */
  float32x4_t r2_safe = vaddq_f32(r2, vdupq_n_f32(FLT_MIN));
  float32x4_t r_inv = vrsqrteq_f32(r2_safe);
  float32x4_t half = vdupq_n_f32(0.5f);
  float32x4_t step = vrsqrtsq_f32(r2_safe, vmulq_f32(r_inv, r_inv));
  r_inv = vmulq_f32(vmulq_f32(half, r_inv), step);
  float32x4_t r = vmulq_f32(r2, r_inv);
  float32x4_t u_lr = vmulq_f32(r, r_s_inv);

  /* Apply long-range correction per lane via scalar kernel_long_grav_eval */
  float f_arr[4], pot_arr[4], u_arr[4];
  vst1q_f32(f_arr, *f_ij);
  vst1q_f32(pot_arr, *pot_ij);
  vst1q_f32(u_arr, u_lr);

  for (int i = 0; i < 4; i++) {
    float corr_f, corr_pot;
    kernel_long_grav_eval(u_arr[i], &corr_f, &corr_pot);
    f_arr[i] *= corr_f;
    pot_arr[i] *= corr_pot;
  }

  *f_ij = vld1q_f32(f_arr);
  *pot_ij = vld1q_f32(pot_arr);
}

#endif /* __ARM_NEON */

/**
 * @brief Computes the intensity of the force at a point generated by a
 * point-mass truncated for long-distance periodicity.
 *
 * The returned quantity needs to be multiplied by the distance vector to obtain
 * the force vector.
 *
 * @param r2 Square of the distance to the point-mass.
 * @param h2 Square of the softening length.
 * @param h_inv Inverse of the softening length.
 * @param h_inv3 Cube of the inverse of the softening length.
 * @param mass Mass of the point-mass.
 * @param r_s_inv Inverse of the mesh smoothing scale.
 * @param f_ij (return) The force intensity.
 * @param pot_ij (return) The potential.
 */
__attribute__((always_inline, nonnull)) INLINE static void
runner_iact_grav_pp_truncated(const float r2, const float h2, const float h_inv,
                              const float h_inv3, const float mass,
                              const float r_s_inv, float *restrict f_ij,
                              float *restrict pot_ij) {

  /* Get the inverse distance */
  const float r_inv = 1.f / sqrtf(r2 + FLT_MIN);
  const float r = r2 * r_inv;

  /* Should we soften ? */
  if (r2 >= h2) {

    /* Get Newtonian gravity */
    *f_ij = mass * r_inv * r_inv * r_inv;
    *pot_ij = -mass * r_inv;

  } else {

    const float ui = r * h_inv;
    const float W_f_ij = kernel_grav_force_eval(ui);
    const float W_pot_ij = kernel_grav_pot_eval(ui);

    /* Get softened gravity */
    *f_ij = mass * h_inv3 * W_f_ij;
    *pot_ij = mass * h_inv * W_pot_ij;
  }

  /* Get long-range correction */
  const float u_lr = r * r_s_inv;
  float corr_f_lr, corr_pot_lr;
  kernel_long_grav_eval(u_lr, &corr_f_lr, &corr_pot_lr);
  *f_ij *= corr_f_lr;
  *pot_ij *= corr_pot_lr;
}

/**
 * @brief Computes the forces at a point generated by a multipole.
 *
 * @param r_x x-component of the distance vector to the multipole.
 * @param r_y y-component of the distance vector to the multipole.
 * @param r_z z-component of the distance vector to the multipole.
 * @param r2 Square of the distance vector to the multipole.
 * @param h The softening length.
 * @param h_inv Inverse of the softening length.
 * @param m The multipole.
 * @param f_x (return) The x-component of the acceleration.
 * @param f_y (return) The y-component of the acceleration.
 * @param f_z (return) The z-component of the acceleration.
 * @param pot (return) The potential.
 */
__attribute__((always_inline, nonnull)) INLINE static void
runner_iact_grav_pm_full(const float r_x, const float r_y, const float r_z,
                         const float r2, const float h, const float h_inv,
                         const struct multipole *m, float *restrict f_x,
                         float *restrict f_y, float *restrict f_z,
                         float *restrict pot) {

  /* Use the M2P kernel */
  struct reduced_grav_tensor l;
  l.F_000 = 0.f;
  l.F_100 = 0.f;
  l.F_010 = 0.f;
  l.F_001 = 0.f;

  gravity_M2P(m, r_x, r_y, r_z, r2, h, /*periodic=*/0, /*rs_inv=*/0.f, &l);

  /* Write back */
  *pot = l.F_000;
  *f_x = l.F_100;
  *f_y = l.F_010;
  *f_z = l.F_001;
}

/**
 * @brief Computes the forces at a point generated by a multipole, truncated for
 * long-range periodicity.
 *
 * @param r_x x-component of the distance vector to the multipole.
 * @param r_y y-component of the distance vector to the multipole.
 * @param r_z z-component of the distance vector to the multipole.
 * @param r2 Square of the distance vector to the multipole.
 * @param h The softening length.
 * @param h_inv Inverse of the softening length.
 * @param r_s_inv The inverse of the gravity mesh-smoothing scale.
 * @param m The multipole.
 * @param f_x (return) The x-component of the acceleration.
 * @param f_y (return) The y-component of the acceleration.
 * @param f_z (return) The z-component of the acceleration.
 * @param pot (return) The potential.
 */
__attribute__((always_inline, nonnull)) INLINE static void
runner_iact_grav_pm_truncated(const float r_x, const float r_y, const float r_z,
                              const float r2, const float h, const float h_inv,
                              const float r_s_inv, const struct multipole *m,
                              float *restrict f_x, float *restrict f_y,
                              float *restrict f_z, float *restrict pot) {

  /* Use the M2P kernel */
  struct reduced_grav_tensor l;
  l.F_000 = 0.f;
  l.F_100 = 0.f;
  l.F_010 = 0.f;
  l.F_001 = 0.f;

  gravity_M2P(m, r_x, r_y, r_z, r2, h, /*periodic=*/1, r_s_inv, &l);

  /* Write back */
  *pot = l.F_000;
  *f_x = l.F_100;
  *f_y = l.F_010;
  *f_z = l.F_001;
}

#endif /* SWIFT_MULTI_SOFTENING_GRAVITY_IACT_H */
